name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git short SHA
        id: meta
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build · products-service
        uses: docker/build-push-action@v5
        with:
          context: ./products-service
          push: false
          tags: products-service:${{ steps.meta.outputs.sha }}

      - name: Build · inventory-service
        uses: docker/build-push-action@v5
        with:
          context: ./inventory-service
          push: false
          tags: inventory-service:${{ steps.meta.outputs.sha }}

      - name: Build · frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          build-args: |
            VITE_PRODUCTS_API_URL=http://localhost:8081
            VITE_INVENTORY_API_URL=http://localhost:8082
            VITE_PRODUCTS_API_KEY=placeholder
            VITE_INVENTORY_API_KEY=placeholder
          tags: frontend:${{ steps.meta.outputs.sha }}

      - name: Summary
        run: |
          echo "### Imágenes construidas :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          echo "| Servicio | Tag |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| products-service | \`${{ steps.meta.outputs.sha }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| inventory-service | \`${{ steps.meta.outputs.sha }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| frontend | \`${{ steps.meta.outputs.sha }}\` |" >> $GITHUB_STEP_SUMMARY
